# Generated by Django 5.2.2 on 2025-11-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
    ]
