# Generated by Django 5.2.2 on 2025-11-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0002_remove_offer_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='offer_app.offer'),
        ),
    ]
