# Generated by Django 5.2.7 on 2025-11-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0003_alter_offerdetail_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
    ]